version: '3.8'
services:
  app:
    build: .
    ports:
      - '70:70'
    depends_on:
        - db
    env_file:
        - .env
  db:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./data/db:/data/db